*** Variables ***
${Path-ImgFile}    C:\\git\\ITrueMart-Wemall\\Resource\\PIC
${PDS_API_URL}    http://products-api.wemall.com:8080
${FMS}            http://products-api.wemall-dev.com
${CAMP_URL}       http://campaign-cms.itruemart.com
${ITM_URL}        http://www.itruemart.com
${ITM_MOBILE_URL}    http://m.itruemart.com
${ITM_URL_SSL}    https://www.itruemart.com
${PCMS_URL}       http://pcms.itruemart.com
${PCMS_URL_HTTP}    pcms.itruemart.com
${PCMS_URL_API}    pcms.itruemart.com
${PCMS_URL_SSL}    https://pcms.itruemart.com
${PCMS_PKEY}      /api/45311375168544
${PCMS_PORT}      80
${HTTP_PROTOCAL}    http
${WEMALL_WEB}     http://www.wemall.com
${WEMALL_MOBILE}    http://m.wemall-dev.com
######### Operation #########
${UPLOADS}        /gen/v1/uploads/
${GEOLOCATIONS}    /gen/v1/geolocations/
${sku_created}    /api/key/v1/sku/create_with_mat_marketplace/
${supplier_created}    /api/key/v1/supplier
${Tokens_API}     /authen/v1/tokens
${CSS_STOREFRONT}    /css/v3/storefronts/
${CSS_SHOP}       /css/v3/shops/
${MEGAMENUS}      /cps/v1/mega-menus/
${MERCHANT_ZONES}    /cps/v1/merchant-zones/
${STATIC_CONTENTS}    /cps/v1/static-contents/
${SHOWROOMS}      /cps/v1/showrooms/
${TEMPLATES}      /cps/v1/templates/
${MENUBARS}       /cps/v1/menubars/
${MERCHANT}       /mch/v1/merchants/
${RETAIL}         retail
${SLUG}           slug/
${PCMS_API_URL}    pcms.itruemart.com
${CAMP_USERNAME}    Thaninart.Chi@ascendcorp.com
${CAMP_PASSWORD}    Nana123
${PCMS_USERNAME}    devitm@itruemart.com
${PCMS_PASSWORD}    1234567
${CAMPS-HOST}     http://campaign-cms.itruemart.com
${PCMS-HOST}      http://pcms.itruemart.com
${WEMALL_HOST}    http://www.wemall.com
